[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=sh -c "python init_db.py && gunicorn --bind 127.0.0.1:8000 --worker-tmp-dir /tmp 'wordrepo.api:create_app()'"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
environment=HOME="/tmp",TMPDIR="/tmp"
priority=10

[program:nginx]
command=nginx -g 'daemon off;' -c /app/deploy/nginx.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
priority=20
